---
- name: "Deploy rocketchat server"
  hosts: rocketchat
  roles:
    - { role: common,       tags: common      }
    - { role: node,         tags: node        }
    - { role: mongodb,      tags: mongodb     }
    - { role: rocketchat,   tags: rocketchat  }
