all:
  hosts:
    rocketchat:
      ansible_host: '<hostname>'
  vars:
    username: '<username>'
    ansible_user: "{{ username }}"
    ansible_become: 'yes'
    ansible_become_method: 'sudo'
    ansible_connection: 'ssh'
    ansible_ssh_pipelining: true
    ansible_python_interpreter: /usr/bin/python3
