---
- name: "Create rocketchat group"
  group:
    name: rocketchat
    state: present

- name: "Create rocketchat user"
  user:
    name: rocketchat
    group: rocketchat
    state: present

- name: "Download rocketchat"
  get_url:
    url: https://releases.rocket.chat/latest/download
    dest: /tmp/rocket.chat.tgz

- name: "Ensures directory exists"
  file:
    path: /opt/Rocket.Chat
    owner: rocketchat
    group: rocketchat
    state: directory

- name: "Extract rocketchat files"
  unarchive:
    src: /tmp/rocket.chat.tgz
    dest: /opt/Rocket.Chat
    remote_src: True
    owner: rocketchat
    group: rocketchat
    extra_opts: [--strip-components=1]

- name: "Install rocketchat"
  npm:
    path: /opt/Rocket.Chat/programs/server

- name: "Change rocketchat ownership"
  file:
    path: /opt/Rocket.Chat
    owner: rocketchat
    group: rocketchat

- name: "Copy rocketchat service"
  copy:
    src: files/rocketchat.service
    dest: /lib/systemd/system
    owner: root
    group: root
    mode: 0644

- name: "Start and enable rocketchat"
  service:
    name: rocketchat
    state: started
    enabled: yes

- name: "Mongodb initiate"
  command: 'mongo --eval "printjson(rs.initiate())"'

- name: "Restart mongodb"
  service:
    name: mongod
    state: restarted
